import os

def configure_signing():
    gradle_path = "android/app/build.gradle"
    
    # We verify the file exists first (it should be generated by flutter create)
    if not os.path.exists(gradle_path):
        print(f"Error: {gradle_path} not found. Ensure 'flutter create' ran first.")
        exit(1)

    print(f"Patching {gradle_path} for signing...")
    
    with open(gradle_path, "r") as f:
        content = f.read()

    # The signing config to inject. 
    # We use System.getenv to read from environment variables or gradle properties.
    # But simpler allows direct reading from key.properties which we will create in the workflow.
    signing_config = """
    signingConfigs {
        release {
            storeFile file("upload-keystore.jks")
            storePassword System.getenv("KEY_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("ALIAS_PASSWORD")
        }
    }
"""

    if "signingConfigs {" in content:
        print("Note: SigningConfigs already present. Skipping block injection.")
    else:
        # Inject before buildTypes (usually safe spot)
        if "buildTypes {" in content:
            content = content.replace("buildTypes {", f"{signing_config}\n    buildTypes {{")
        else:
            print("Error: Could not find buildTypes block to inject signing config.")
            exit(1)

    # Replace the debug signing config with release
    # Standard flutter template uses: signingConfig signingConfigs.debug
    old_config = "signingConfig signingConfigs.debug"
    new_config = "signingConfig signingConfigs.release"
    
    if old_config in content:
        content = content.replace(old_config, new_config)
        print("Switched release build type to use release signing config.")
    else:
        print("Warning: Could not find 'signingConfig signingConfigs.debug' to replace. Might need manual check.")

    with open(gradle_path, "w") as f:
        f.write(content)

    print("Successfully configured signing in build.gradle.")

if __name__ == "__main__":
    configure_signing()
